;;; Dump of interface repository generated by dump-ifr.lisp

(provide 'loadidl-cddr_01-rest)

(require 'corba)

(corba-load-repository '
(repository nil
 (module "::CDDR_01"
  (union "::CDDR_01::Sexp"
         (:tk_union "IDL:CDDR_01/Sexp:1.0" "Sexp" (:tk_short) -1
          ((0 "any_val" (:tk_any))
           (1 "list_val"
            (:tk_alias "IDL:CDDR_01/List:1.0" "List"
             (:tk_sequence "IDL:CDDR_01/Sexp:1.0" 0)))
           (2 "symbol_val" (:tk_string 0)) (10 "long_val" (:tk_long))
           (11 "double_val" (:tk_double)) (12 "string_val" (:tk_string 0))
           (13 "object_val"
            (:tk_objref "IDL:omg.org/CORBA/Object:1.0" "Object")))))
  (type "::CDDR_01::List" "IDL:CDDR_01/List:1.0")
  (interface "::CDDR_01::RestSexp" nil
   (:tk_objref "IDL:CDDR_01/RestSexp:1.0" "RestSexp")
   (operation "get" :op_normal "IDL:CDDR_01/Sexp:1.0" nil nil)
   (operation "getq" :op_normal "IDL:CDDR_01/Sexp:1.0"
    (("q" :param_in "IDL:CDDR_01/Sexp:1.0")) nil)
   (operation "put" :op_normal (:tk_void)
    (("s" :param_in "IDL:CDDR_01/Sexp:1.0")) nil)
   (operation "delete" :op_normal (:tk_void) nil nil)
   (operation "insert" :op_normal "IDL:CDDR_01/Sexp:1.0"
    (("s" :param_in "IDL:CDDR_01/Sexp:1.0")) nil))
  (interface "::CDDR_01::RestAny" nil
   (:tk_objref "IDL:CDDR_01/RestAny:1.0" "RestAny")
   (operation "get" :op_normal (:tk_any) nil nil)
   (operation "getq" :op_normal (:tk_any) (("q" :param_in (:tk_any))) nil)
   (operation "put" :op_normal (:tk_void) (("s" :param_in (:tk_any))) nil)
   (operation "delete" :op_normal (:tk_void) nil nil)
   (operation "insert" :op_normal (:tk_any) (("s" :param_in (:tk_any))) nil)))))

