;;; loadidl-coseventchanneladmin.el -- generated by corba.el's corba-make-loadidl

(provide 'loadidl-coseventchanneladmin)
(require 'loadidl-coseventcomm)

(corba-load-repository
  '(module "::CosEventChannelAdmin"
        (exception "::CosEventChannelAdmin::AlreadyConnected"
                   (:tk_except "IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0" "AlreadyConnected" nil))
        (exception "::CosEventChannelAdmin::TypeError"
                   (:tk_except "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0" "TypeError" nil))
        (interface "::CosEventChannelAdmin::ProxyPushConsumer"
                   ("IDL:omg.org/CosEventComm/PushConsumer:1.0")
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/ProxyPushConsumer:1.0" "ProxyPushConsumer")
                   (operation "connect_push_supplier" :OP_NORMAL
                              (:tk_void)
                              (("push_supplier" :PARAM_IN
                                (:tk_objref "IDL:omg.org/CosEventComm/PushSupplier:1.0" "PushSupplier")))
                              ("IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0")))
        (interface "::CosEventChannelAdmin::ProxyPullSupplier"
                   ("IDL:omg.org/CosEventComm/PullSupplier:1.0")
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/ProxyPullSupplier:1.0" "ProxyPullSupplier")
                   (operation "connect_pull_consumer" :OP_NORMAL
                              (:tk_void)
                              (("pull_consumer" :PARAM_IN
                                (:tk_objref "IDL:omg.org/CosEventComm/PullConsumer:1.0" "PullConsumer")))
                              ("IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0")))
        (interface "::CosEventChannelAdmin::ProxyPullConsumer"
                   ("IDL:omg.org/CosEventComm/PullConsumer:1.0")
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/ProxyPullConsumer:1.0" "ProxyPullConsumer")
                   (operation "connect_pull_supplier" :OP_NORMAL
                              (:tk_void)
                              (("pull_supplier" :PARAM_IN
                                (:tk_objref "IDL:omg.org/CosEventComm/PullSupplier:1.0" "PullSupplier")))
                              ("IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0" "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0")))
        (interface "::CosEventChannelAdmin::ProxyPushSupplier"
                   ("IDL:omg.org/CosEventComm/PushSupplier:1.0")
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/ProxyPushSupplier:1.0" "ProxyPushSupplier")
                   (operation "connect_push_consumer" :OP_NORMAL
                              (:tk_void)
                              (("push_consumer" :PARAM_IN
                                (:tk_objref "IDL:omg.org/CosEventComm/PushConsumer:1.0" "PushConsumer")))
                              ("IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0" "IDL:omg.org/CosEventChannelAdmin/TypeError:1.0")))
        (interface "::CosEventChannelAdmin::ConsumerAdmin" nil
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/ConsumerAdmin:1.0" "ConsumerAdmin")
                   (operation "obtain_push_supplier" :OP_NORMAL "IDL:omg.org/CosEventChannelAdmin/ProxyPushSupplier:1.0" nil nil)
                   (operation "obtain_pull_supplier" :OP_NORMAL "IDL:omg.org/CosEventChannelAdmin/ProxyPullSupplier:1.0" nil nil))
        (interface "::CosEventChannelAdmin::SupplierAdmin" nil
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/SupplierAdmin:1.0" "SupplierAdmin")
                   (operation "obtain_push_consumer" :OP_NORMAL "IDL:omg.org/CosEventChannelAdmin/ProxyPushConsumer:1.0" nil nil)
                   (operation "obtain_pull_consumer" :OP_NORMAL "IDL:omg.org/CosEventChannelAdmin/ProxyPullConsumer:1.0" nil nil))
        (interface "::CosEventChannelAdmin::EventChannel" nil
                   (:tk_objref "IDL:omg.org/CosEventChannelAdmin/EventChannel:1.0" "EventChannel")
                   (operation "for_consumers" :OP_NORMAL "IDL:omg.org/CosEventChannelAdmin/ConsumerAdmin:1.0" nil nil)
                   (operation "for_suppliers" :OP_NORMAL "IDL:omg.org/CosEventChannelAdmin/SupplierAdmin:1.0" nil nil)
                   (operation "destroy" :OP_NORMAL
                              (:tk_void)
                              nil nil)))
)


;;; loadidl-coseventchanneladmin.el ends here
