;;; Dump of interface repository generated by dump-ifr.lisp

(require 'corba)

(corba-load-repository '
(repository nil
 (module "::CDDR_01"
  (interface "::CDDR_01::SimpleQueue" nil
   (:tk_objref "IDL:CDDR_01/SimpleQueue:1.0" "SimpleQueue")
   (operation "enqueue" :op_normal (:tk_void)
    (("msg" :param_in (:tk_string 0))) nil)
   (operation "dequeue" :op_normal (:tk_string 0)
    (("non_blocking" :param_in (:tk_boolean))
     ("flag" :param_out (:tk_boolean)))
    nil)
   (operation "alloc_id" :op_normal (:tk_long) (("n" :param_in (:tk_long)))
    nil)
   (operation "put" :op_normal (:tk_boolean)
    (("id" :param_in (:tk_long)) ("msg" :param_in (:tk_string 0))) nil)
   (operation "get" :op_normal (:tk_string 0) (("id" :param_in (:tk_long)))
    nil)
   (operation "ack" :op_normal (:tk_void) (("id" :param_in (:tk_long))) nil)))))


(provide 'loadidl-cddr_01-queue)

;;; loadidl-cddr_01-queue.el ends here
